### ISSUE TITLE
Horizon ignored by `did_imputation`?

### ISSUE THREAD

**Issue by gn0** [kylebutts/didimputation#11]
Hi Kyle,

I am looking at [lines 154 through 158](https://github.com/kylebutts/didimputation/blob/295e48365958bd02a3067fcf3926e7dd96f17c7e/R/did_imputation.R#L154) in `R/did_imputation.R`:

```
      # allhorizons
      if (all(horizon == TRUE)) horizon <- event_time

      # Create wtr of horizons
      wtr <- paste0("zz000wtr", event_time[event_time >= 0])
```

`horizon` is assigned on line 155 but never used again.  Is line 158 meant to say

```
      wtr <- paste0("zz000wtr", horizon[horizon >= 0])
```

instead?

Thank you,
Gabor

**Comment by kylebutts** [comment]
Yep, thanks! Fixed in 158eb51

**Comment by shoonlee** [comment]
Hi Kyle,

Thanks for the great package! Maybe this is related to the point made earlier in this thread, but the vector value for ```horizon``` doesn't seem to affect the result. For instance, the following two codes produce the same result for me. 

```
did_imputation(data = df_hom, yname = "dep_var", gname = "g",
               tname = "year", idname = "unit", pretrends = -5:-1, horizon = TRUE)

did_imputation(data = df_hom, yname = "dep_var", gname = "g",
               tname = "year", idname = "unit", pretrends = -5:-1, horizon = 0:5)
```

Just in case, I did the same in Stata, and there, the post period is presented as expected. 

Is this indeed related to the discussion above?

**Comment by kylebutts** [comment]
@shoonlee Are you using the latest version from GitHub? You can use `devtools::install_github("kylebutts/didimputation")`.

**Comment by shoonlee** [comment]
Ah, thank you. I had trouble with ```devtools::install_github("kylebutts/didimputation")``` after R 4.2.2 upgrade, but I'll make sure to check the newer version of ```didimputation```.
