### ISSUE TITLE
Retrieving pre-trends in did_imputation

### ISSUE THREAD

**Issue by Irazall** [kylebutts/didimputation#12]
Thank you very much for implementing this helpful method! As I am a no good Stata programmer, I really like that there is a R solution.

Currently, I struggle with the implementation of the pretrends. As far as I understand, you get them directly in Stata. In R I see the coefficients together with the standard errors and confidence intervals in the function output of `did_imputation`. Unfortunately, these information is not enough to calculate a F-statistic to test whether all pre-trend coefficients are zero. 

It would be great if `did_imputation` would return the whole first-stage model or at least the joint F-statistic of the pre-trend coefficients similar to the Stata implementation. Is it planned to be implemented in near future? This would really facilitate my work.

Thank you in advance!

**Comment by kylebutts** [comment]
You can run the pre-treatment estimator using the following:

```{r}
pre_est <- fixest::feols(
  y ~ i(event_time) | id + year, 
  data[data$treat == 0, ],
  weights = ~weight, warn = FALSE, notes = FALSE
)
```

**Comment by Irazall** [comment]
Thank you for your quick reply. How do calculate the variable `event_time`? I don't have it in my data but just the `year`.

**Comment by kylebutts** [comment]
`event_time` is tear relative to treatment, i.e. event time -1 is one year prior to treatment. If you have a variable `year` and a variable `year_treated`, `event_time` is just `year_treated` - `year`

**Comment by Irazall** [comment]
But what in the case of never treated units? Did I get it right that you put `event_time` as infinity then? And why not just `NA`?

**Comment by kylebutts** [comment]
Some people but them as `event_time` -1, since that's usually the reference period. I tend to put them at `-Inf` since their `year_treated` is infinity in Callaway and Sant'Anna notation. Infinity works as well.

`NA` does not work because those observations would be dropped from the regression.

**Comment by Irazall** [comment]
Thank you very much :) This helped a lot! I can work with this now
