### ISSUE TITLE
Last graph of ("DID Imputation Estimate" , "True Effect" , "TWFE Estimate")

### ISSUE THREAD

**Issue by AlejandraPP** [kylebutts/didimputation#13]
Hello Kyle Butts, here Alejandra.

Could it be possible that the last graph under [README.md](https://github.com/kylebutts/didimputation/blob/main/README.md) could be missing the third "TWFE Estimate" dots?

When reproducing your code, I got something like this: 
![DID Imputation Estimate, True Effect, TWFE Estimate](https://github.com/kylebutts/didimputation/assets/133754124/b52f6205-468f-4560-8231-5129a4065354)

Apologies in advance if it was me who made the mistake.
PS: I had to modify a bit the code in version 4.2.3. to make DT() to work.

Best,
Alejandra

**Comment by kylebutts** [comment]
Ahh, yeah definitely! Could you pull request the updated code and I'll merge in?

**Comment by AlejandraPP** [comment]
Sure thing. You just need to replace from the #TWFE line

`twfe <- fixest::feols(dep_var ~ i(rel_year, ref = c(-1, Inf)) | unit + year, data = df_het)

twfe_est <- broom::tidy(twfe)

twfe_est <- twfe_est %>%
  dplyr::filter(grepl("rel_year::", term)) %>%
  dplyr::select(term, estimate, std.error) %>%
  dplyr::mutate(
    rel_year = as.numeric(stringr::str_remove(term, "rel_year::")),
    ci_lower = estimate - 1.96 * std.error,
    ci_upper = estimate + 1.96 * std.error,
    group = "TWFE Estimate"
  ) %>%
  dplyr::filter(rel_year <= 8 & rel_year >= -8) %>%
  dplyr::mutate(rel_year = rel_year - 0.1)

# Add TWFE Points
both_pts <- rbind(pts, twfe_est, fill = TRUE)

max_y <- max(pts$estimate)

ggplot() +
  # 0 effect
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = -0.5, linetype = "dashed") +
  # Confidence Intervals
  geom_linerange(data = both_pts, mapping = aes(x = rel_year, ymin = ci_lower, ymax = ci_upper), color = "grey30") +
  # Estimates
  geom_point(data = both_pts, mapping = aes(x = rel_year, y = estimate, color = group), size = 2) +
  # Label
  geom_label(
    data = data.frame(x = -0.5 - 0.1, y = max_y + 0.25, label = "Treatment Starts ▶"),
    label.size = NA,
    mapping = aes(x = x, y = y, label = label),
    size = 5.5,
    hjust = 1,
    fontface = 2,
    inherit.aes = FALSE
  ) +
  scale_x_continuous(breaks = -8:8, minor_breaks = NULL) +
  scale_y_continuous(minor_breaks = NULL) +
  scale_color_manual(
    values = c(
      "DID Imputation Estimate" = "steelblue",
      "True Effect" = "#b44682",
      "TWFE Estimate" = "#82b446"
    )
  ) +
  labs(x = "Relative Time", y = "Estimate", color = NULL, title = NULL) +
  theme_minimal(base_size = 16) +
  theme(legend.position = "bottom")
#> Warning: Removed 17 rows containing missing values (`geom_segment()`).`

**Comment by AlejandraPP** [comment]
Hey @kylebutts,
it looks like I do not have rights to open a branch/ pull request. 
I think all that is to be changed is to update the image you have in the ReadMe. I will attach my graph below.
![README-plot-compare-1](https://github.com/kylebutts/didimputation/assets/133754124/301e94ad-fb4c-478e-b44a-afd3a4a881de)

**Comment by kylebutts** [comment]
Thanks @AlejandraPP. Should be fixed now; the code was erroring that I had miseed

**Comment by kylebutts** [comment]
Thanks @AlejandraPP. Should be fixed now; the code was erroring that I had miseed

**Comment by kylebutts** [comment]
Thanks @AlejandraPP. Should be fixed now; the code was erroring that I had miseed
