### ISSUE TITLE
Unnecessary env call?

### ISSUE THREAD

**Issue by shoshievass** [kylebutts/didimputation#14]
Hey @kylebutts, can you explain why you have the `env = list(e = e)` in line 144 (https://github.com/kylebutts/didimputation/blob/b65c8ab2cc09580e89bb812f29d998610e45931f/R/did_imputation.R#LL144C10-L144C28)?

It's generating the following error for me, and things seem to work fine if I exclude it.

```
>>Error in `[.data.table`(data, , `:=`(paste0("zz000wtr", e), ifelse(is.na(zz000event_time),  : 
  unused argument (env = list(e = e))
```

**Comment by kylebutts** [comment]
Hi, if you update to dev version of `data.table` this error should go away!
