### ISSUE TITLE
issue with term in event study output

### ISSUE THREAD

**Issue by 95goo** [kylebutts/didimputation#15]
hi, thank you for this amazing package Kyle. its been so helpful. I have a staggered diff-in-diff, and I am trying to run event study using the package. my code is as follows:

`did_imputation(even_study_data,
yname = "outcome",
gname = "treated_date",
tname = "month_year",
idname = "id",
cluster_var = "state",
horizon = TRUE)`

Outcome is a double.

Treated_date is NA values for the state that does not receive treatment.  It is possible for individuals to move between states, so sometimes, for a given month they can be treated and then they can go back to be untreated if they then go to an untreated state. I have no other NA in my data. 

Thankfully my code runs! 

my issue is very strange output in the "term" variable. as seen below, the term is not sequential and it is not even the correct number of time periods. i only have 16 unique month and year in my input data, so unsure why theres 20 rows. any guidance or advice would be much appreciated -thank you.
<img width="66" alt="Screen Shot 2023-06-20 at 2 44 14 PM" src="https://github.com/kylebutts/didimputation/assets/133628982/bc3a7dc1-0e8c-4e41-87d6-a370e31e5201">

**Comment by kylebutts** [comment]
Hi @95goo, the nature of the data is the problem. What you're describing is a non-staggered treatment (off, on, and off again). I assume that's what is creating the problem.

Ignoring that (which shouldn't be ignored), how is the variable `month_year` stored? The term variable is defined as `month_year - treated_date`, so start there and look at the values

**Comment by 95goo** [comment]
oh ok.. thank you..  let me think about the first issue more. 

But the month_year is stored as a double(class is date), while treated_date is stored as a  double(class is date) too. 
The variables look like "2020-01-01", "2020-02-01", as so on.
There is no duplicate individual + month_year in the dataset, but depending on what state an individual is in for a given month, they could have different treatment_date. 

<img width="127" alt="Screen Shot 2023-06-21 at 8 04 56 AM" src="https://github.com/kylebutts/didimputation/assets/133628982/20871951-81ad-4a96-8545-1f6e521d2d48">

**Comment by 95goo** [comment]
given month_year and _treated_date are in "ymd" data classes, when you subtract them, the values are like "-400 days", "-500" days etc. Thank you very much for your help. Do you have any recommendation on how to circumvent this specific issue if treatment is rolled out on month level? Thanks for all your help

**Comment by kylebutts** [comment]
You could coerce the dates into months since the starting month of your sample (1 being the first month of the sample, 2 being the next, and so on). The `{lubridate}` package should help with that.
