### ISSUE TITLE
standard errors in pre-trend estimation not clustered?

### ISSUE THREAD

**Issue by paustefa** [kylebutts/didimputation#18]
Hi Kyle,

thanks so much for this great package! I have one small question. It seems to me that standard errors are currently not clustered when computing pre-trend coefficients. Or am I missing something?

Basically, should lines 282 onwards in did_imputation look something like this (with the cluster argument)?

`
pre_est <- fixest::feols(
pre_formula, data[data$zz000treat == 0, ],
weights = ~zz000weight, warn = FALSE, notes = FALSE, cluster=cluster_var
)
`

Thanks again!

Stefan

**Comment by kylebutts** [comment]
Yep, thanks Stefan
