### ISSUE TITLE
Pre-trends computation causes error

### ISSUE THREAD

**Issue by owmork** [kylebutts/didimputation#19]
Hi Kyle,

thanks for the package! 

I noticed an error when specifying pre-trends with the development version (see attached). From my understanding, the problem arises in `did_imputation()` at `pre_out = pre_est$coeftable` which should be a data frame like object (and not a matrix) to be combined with `pre_out$term = names(pre_est$coefficients)` and `pre_out$lhs <- yvars`. Wrapping it `data.frame()` works for me: `pre_out = as.data.frame(pre_est$coeftable)`.

On a different note, because it only raises a warning and I think it is not worth to open another issue: when the name of the supplied `wtr` cannot be converted to a numeric, the warning `Warning message: In eval(sub, parent.frame(), parent.frame()) : NAs introduced by coercion` is raised. And if I understand it correctly, `wtr` could potentially be used to compute something like covariate-specific treatment effects, which could be categorical (e.g. creating weights for male/female treated units)?

``` r
#devtools::install_github("kylebutts/didimputation")
library(didimputation)
#> Loading required package: fixest
#> Warning: package 'fixest' was built under R version 4.3.2
#> Loading required package: data.table
#> Warning: package 'data.table' was built under R version 4.3.2
```

``` r

dyn <- did_imputation(
    data = df_het,
    yname = "dep_var",
    gname = "g",
    tname = "year",
    idname = "unit",
    # event-study
    horizon = TRUE,
    pretrends = -5:-1
)
#> Warning in pre_out$term <- names(pre_est$coefficients): Coercing LHS to a list
#> Error: All elements in argument 'x' to 'setDT' must be of same length, but the profile of input lengths (length:frequency) is: [5:1, 1:21]
#> The first entry with fewer than 5 entries is 1.
```

<sup>Created on 2024-07-15 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by kylebutts** [comment]
Hi @owmork, thanks. It appears `fixest` changed and made this error. It's fixed now.

To answer your question re `wtr`, these need to be a numeric variable. I think you're asking something like "what if I want to average just for male/female units. That can be done with dummy variables for each gender (e.g. 0 for male, 1 for female). 

I could perhaps add that feature, but don't have the time to do so
