### ISSUE TITLE
Option to cluster standard errors

### ISSUE THREAD

**Issue by emugmor** [kylebutts/didimputation#2]
Thank you so much for creating this package! My team at work was previously using the `didimputation` package in Stata, and this package was very helpful when we moved our code over to R. 

The one functionality that we needed that didn't transfer was the ability to cluster the standard errors. I was able to add this functionality by adding a `cluster_var` argument to `did_imputation` and replaced `idname` with `cluster_var` in Equation 8:

```
# Equation (8)
# Calculate variance of estimate
split_id <- split(data, data[[cluster_var]], drop = T) 
results <- lapply(split_id, function(x) {
	temp = sum(x$zz000v * x$zz000tau_centered)^2
	return(temp)
})
```

The results replicate the Stata results perfectly. Sharing here in case anyone else has had the same issue.

**Comment by kylebutts** [comment]
Thanks for that. I added it to the github version.
