### ISSUE TITLE
Return VCov 

### ISSUE THREAD

**Issue by eohne** [kylebutts/didimputation#20]
Hi Kyle
Again thanks for making all of these models available in R!

Is there a way to get a vcov matrix from the call to did_imputation?  I would like to do some multiple hypothesis tests on the leads and lags. Potentially also test whether the cumulative effects are significant - although not one hundred percent sure yet how I would go about that. 

Thanks for all your work.

**Comment by kylebutts** [comment]
Hi Elias,

Since the pre-treatment and post-treatment estimates are run using separate regressions, it is not so easy to do. However, you can bootstrap the estimator to get the vcov and do as you wish.

**Comment by eohne** [comment]
Hi Kyle,

Thanks for getting back to me so quickly. 

That is what I feared. I will go the bootstrapping route then.

Thanks
