### ISSUE TITLE
Too large imput matrix for SpMat()

### ISSUE THREAD

**Issue by eliascis** [kylebutts/didimputation#6]
I have a data set with over 28000 units across 10 years. 
Running `did_imputation` the following error message is created:
```
Error in make_V_star((Z * data[, zz000weight]), (Z * data[, zz000weight])[data$zz000treat ==  : 
  SpMat::init(): requested size is too large; suggest to enable ARMA_64BIT_WORD
```
Some solutions suggests to include in the Cpp code 
`#define ARMA_64BIT_WORD 1 `
before
`#include <RcppArmadillo.h>`
See for example this post: https://stackoverflow.com/questions/40592054/large-matrices-in-rcpparmadillo-via-the-arma-64bit-word-define.

For replication, I have attached my data (anonymized). 
Here is the code I run: 
```
d<-readRDS("gitexample.csv")
table(d$year)
table(d$year,d$cohort,useNA="always")
e<-did_imputation(
  data=d,
  yname="outcome",
  gname="cohort",
  tname="year",
  idname="id"
)
```

[gitexample.csv](https://github.com/kylebutts/didimputation/files/9152192/gitexample.csv)

**Comment by kylebutts** [comment]
Let me know if this doesn't work, but should be fixed: 3ac3b35d4bc43b26d66a1e395bd496159d81f6a1

**Comment by eliascis** [comment]
@kylebutts The command starts without an error message, though it hasn't completed after several hours.

**Comment by kylebutts** [comment]
@eliascis If you use my other package `did2s`, you will get identical point estimates and slightly different standard errors. That package has received more attention by me, so it should be faster!
